export const CREATE_BOOK = "BOOK/CREATE_BOOK";
export const FIND_BOOK = "BOOK/FIND_BOOK";
export const HIDE_BOOK = "BOOK/HIDE_BOOK";
export const FILL_BOOKS = "BOOK/FILL_BOOKS";
export const SET_CURRENT_BOOK = "BOOK/SET_CURRENT_BOOK";
export const MOVE_BOOK_TO_TOP = "BOOK/MOVE_BOOK_TO_TOP";

export const FETCH_NOTES = "NOTES/FETCH_NOTES";
export const CREATE_NOTE = "NOTE/CREATE_NOTE";
export const EDIT_NOTE = "NOTE/EDIT_NOTE";
export const DELETE_NOTE = "NOTE/DELETE_NOTE";
export const CLEAR_NOTES = "NOTE/CLEAR_NOTES";

export const ENTER_PASSWORD = "APP/ENTER_PASSWORD";
export const LOCK_BOOK = "APP/LOCK_BOOK";
export const SET_SHOWING_SETTINGS = "APP/SET_SHOWING_SETTINGS";
export const SET_CURRENT_OPENING_TAB = "APP/SET_CURRENT_OPENING_TAB";
export const SET_NOTES_OVER = "APP/SET_NOTES_OVER";

export const SET_EDIT_ACTION = "SETTING/SET_EDIT_ACTION";
export const SET_DELETE_ACTION = "SETTING/SET_DELETE_ACTION";
